/// <reference types="vitest" />
import { defineConfig } from "vitest/config";
import { resolve } from "node:path";
import react from "@vitejs/plugin-react";

export default defineConfig({
    plugins: [react()],
    resolve: {
        alias: { "@": resolve(__dirname, "src") },
    },
    test: {
        environment: "jsdom",
        globals: true,
        setupFiles: ["./test/setup.ts"],
        // Explicit include so `e2e/` stays out: it holds Playwright specs (real
        // browser, own runner) that Vitest would collect and fail on for the
        // missing Playwright fixtures. `bin/` carries the OpenAPI codegen tests.
        include: ["src/**/*.test.{ts,tsx}", "bin/**/*.test.mjs"],
        css: { modules: { classNameStrategy: "non-scoped" } },
        coverage: {
            provider: "v8",
            reporter: ["text", "html"],
            include: ["src/**/*.{ts,tsx}"],
            exclude: [
                "src/**/*.test.{ts,tsx}",
                "src/**/index.ts",
                "src/types.d.ts",
                // `src/vision/` is a vendored copy of ort-vision-sdk-web
                // (regenerated by `npm run vendor:vision`, tested upstream).
                // Only the SDK's own additions there — `public.ts`, the camera
                // and luminance hooks — stay measured.
                "src/vision/core/**",
                "src/vision/io/**",
                "src/vision/postprocess/**",
                "src/vision/preprocess/**",
                "src/vision/tasks/**",
                "src/vision/labels.ts",
                "src/vision/results.ts",
                "src/vision/types.ts",
            ],
            /**
             * Floors set just under the current numbers so a regression fails
             * the build while ordinary churn does not. Raise them when coverage
             * climbs — never lower them to make a red build green.
             */
            thresholds: {
                lines: 96,
                statements: 94,
                functions: 94,
                branches: 89,
            },
        },
    },
});
