import type { IconName } from "./generated/icon-name";

/**
 * The slug `fromMaterialSymbol` falls back to when a code is unknown.
 *
 * A neutral glyph rather than nothing: a category created in an admin with a
 * code this table has not learned yet still has to draw something, or it opens a
 * hole in the grid and the bug reads as a layout problem instead of a missing
 * mapping.
 *
 * Lucide's `circle-help` is a deprecated alias of this slug. `<Icon>` resolves
 * aliases, so both render — but the bridge emits the canonical name, since a
 * value that gets persisted should not be one lucide has already renamed.
 */
export const MATERIAL_SYMBOL_FALLBACK: IconName = "circle-question-mark";

/**
 * Material Symbols code → lucide slug, for backends that store `icon_code`.
 *
 * Every Python backend we write stores a category icon as a Material Symbol
 * (`build`, `format_paint`, `electrical_services`) — the vocabulary Flutter,
 * Android and the administrative seeds already speak. The SDK speaks lucide in
 * kebab-case. The two lists do not meet, and the failure is nastier than an
 * empty screen: a handful of codes collide by accident, so roughly one row in
 * ten draws the right icon and the bug reads as "some icons went missing".
 *
 * **Still not the full vocabulary.** Material Symbols ships ~3600 names and
 * almost none of them will ever appear in an `icon_code` of ours, so this grows
 * on demand, one hand-written pair at a time — a map generated by name
 * heuristics gets it badly wrong, starting with `build`, which is a wrench in
 * Material Symbols and nothing to do with construction. What is here covers the
 * trades lot it started as plus the vocabulary an administrative panel actually
 * uses: navigation, money, dates, media, and the service categories a seed
 * tends to carry.
 *
 * Every target is checked mechanically against the slug list by
 * `material-symbols.test.ts`, so a pair pointing at a name lucide does not ship
 * — or at one it has since deprecated — fails the suite instead of reaching a
 * grid. What no test can check is whether the *chosen* icon is the right
 * metaphor, which is why pairs go in by hand.
 *
 * **Approximations, deliberate and not one-to-one** (the full list lives in
 * `docs/icons.md`):
 *
 * - `plumbing` → `shower-head`, because lucide has no pipe.
 * - `build`, `handyman` and `hardware` all land on `wrench` — Material Symbols
 *   distinguishes the tools, lucide does not.
 * - `pedal_bike`, `two_wheeler` and `delivery_dining` all land on `bike`.
 * - `dentistry` → `face-slightly-smiling`, since lucide ships no tooth.
 * - `iron` → `shirt` and `cleaning_services` → `spray-can`: the activity, not
 *   the implement.
 * - `roofing` → `house`, the same glyph as `home`, because lucide has no roof.
 *
 * The identity pairs are here on purpose. Their names happen to match in both
 * vocabularies, so they already render today — leaving them out would send them
 * to {@link MATERIAL_SYMBOL_FALLBACK} and make this bridge a regression for
 * exactly the codes that used to work.
 *
 * @see fromMaterialSymbol — the lookup you normally call.
 */
export const materialToLucide: Readonly<Record<string, IconName>> = {
    ac_unit: "snowflake",
    account_balance: "landmark",
    add: "plus",
    balance: "scale",
    bar_chart: "chart-column",
    battery_full: "battery-full",
    bluetooth: "bluetooth",
    bolt: "zap",
    brush: "brush",
    build: "wrench",
    cake: "cake",
    calculate: "calculator",
    campaign: "megaphone",
    car_repair: "car",
    carpenter: "hammer",
    chair: "armchair",
    chat: "message-circle",
    check: "check",
    child_care: "baby",
    cleaning_services: "spray-can",
    close: "x",
    cloud: "cloud",
    code: "code",
    computer: "monitor",
    construction: "hard-hat",
    content_cut: "scissors",
    credit_card: "credit-card",
    dashboard: "layout-dashboard",
    delete: "trash-2",
    delivery_dining: "bike",
    dentistry: "face-slightly-smiling",
    description: "file-text",
    directions_car: "car",
    door_front: "door-open",
    download: "download",
    edit: "pencil",
    electrical_services: "plug-zap",
    error: "circle-x",
    event: "calendar",
    favorite: "heart",
    fitness_center: "dumbbell",
    flight: "plane",
    folder: "folder",
    format_paint: "paint-roller",
    forum: "messages-square",
    gavel: "gavel",
    grass: "sprout",
    group: "users",
    groups: "users",
    handyman: "wrench",
    hardware: "wrench",
    help: "circle-question-mark",
    history: "rotate-ccw-clock",
    home: "house",
    hotel: "bed-double",
    image: "image",
    info: "info",
    iron: "shirt",
    key: "key",
    kitchen: "refrigerator",
    laptop: "laptop",
    local_bar: "wine",
    local_cafe: "coffee",
    local_florist: "flower",
    local_gas_station: "fuel",
    local_laundry_service: "washing-machine",
    local_shipping: "truck",
    local_taxi: "car-taxi-front",
    location_on: "map-pin",
    lock: "lock",
    lock_open: "lock-open",
    login: "log-in",
    logout: "log-out",
    mail: "mail",
    map: "map",
    medical_services: "stethoscope",
    menu: "menu",
    mic: "mic",
    music_note: "music",
    notifications: "bell",
    palette: "palette",
    payments: "banknote",
    pedal_bike: "bike",
    person: "user",
    pest_control: "bug",
    pets: "paw-print",
    phone: "phone",
    phone_iphone: "smartphone",
    photo_camera: "camera",
    pie_chart: "chart-pie",
    plumbing: "shower-head",
    print: "printer",
    receipt_long: "receipt",
    restaurant: "utensils",
    roofing: "house",
    router: "router",
    savings: "piggy-bank",
    schedule: "clock",
    school: "graduation-cap",
    search: "search",
    security: "shield-check",
    settings: "settings",
    share: "share-2",
    shield: "shield",
    shopping_bag: "shopping-bag",
    shopping_cart: "shopping-cart",
    smartphone: "smartphone",
    soap: "soap-dispenser-droplet",
    spa: "flower-2",
    star: "star",
    store: "store",
    storefront: "store",
    support_agent: "headset",
    sync: "refresh-cw",
    today: "calendar-days",
    translate: "languages",
    trending_up: "trending-up",
    tv: "tv",
    two_wheeler: "bike",
    upload: "upload",
    vaccines: "syringe",
    verified: "badge-check",
    videocam: "video",
    visibility: "eye",
    warehouse: "warehouse",
    warning: "triangle-alert",
    water_drop: "droplet",
    wifi: "wifi",
    work: "briefcase",
    yard: "trees",
};

/**
 * Translate a Material Symbols code into a lucide slug, always returning one.
 *
 * Never returns `undefined`: an unknown code resolves to `fallback`, so a row
 * whose `icon_code` this table has not learned yet still renders. The input is
 * trimmed and lower-cased before lookup, because a seed written by hand is the
 * kind of source that carries stray whitespace and the odd capital.
 *
 * Nothing else in `/icons` imports this module, so an app that does not store
 * Material Symbols never pays for the table.
 *
 * @example
 * <Icon name={fromMaterialSymbol(category.icon_code)} size={20} />
 *
 * @example
 * <Icon name={fromMaterialSymbol(category.icon_code, "folder")} size={20} />
 *
 * @param code - A Material Symbols name, or `null`/`undefined` for a row that has none.
 * @param fallback - Slug to use when `code` is empty or unknown. Defaults to {@link MATERIAL_SYMBOL_FALLBACK}.
 * @returns A lucide slug `<Icon>` can render.
 */
export function fromMaterialSymbol(
    code: string | null | undefined,
    fallback: IconName = MATERIAL_SYMBOL_FALLBACK,
): IconName {
    if (!code) return fallback;
    return materialToLucide[code.trim().toLowerCase()] ?? fallback;
}
