import type { IconName } from "./generated/icon-name";

/**
 * The slug `fromMaterialSymbol` falls back to when a code is unknown.
 *
 * A neutral glyph rather than nothing: a category created in an admin with a
 * code this table has not learned yet still has to draw something, or it opens a
 * hole in the grid and the bug reads as a layout problem instead of a missing
 * mapping.
 *
 * Lucide's `circle-help` is a deprecated alias of this slug. `<Icon>` resolves
 * aliases, so both render — but the bridge emits the canonical name, since a
 * value that gets persisted should not be one lucide has already renamed.
 */
export const MATERIAL_SYMBOL_FALLBACK: IconName = "circle-question-mark";

/**
 * Material Symbols code → lucide slug, for backends that store `icon_code`.
 *
 * Every Python backend we write stores a category icon as a Material Symbol
 * (`build`, `format_paint`, `electrical_services`) — the vocabulary Flutter,
 * Android and the administrative seeds already speak. The SDK speaks lucide in
 * kebab-case. The two lists do not meet, and the failure is nastier than an
 * empty screen: a handful of codes collide by accident, so roughly one row in
 * ten draws the right icon and the bug reads as "some icons went missing".
 *
 * **Which codes are here, and why those.** Material Symbols ships ~6100 names.
 * The keys below are the head of that list ranked by Google's own published
 * popularity (`fonts.google.com/metadata/icons`), which is real usage data rather
 * than a guess at which names a seed will contain. Every key was checked to exist
 * in that vocabulary and every target to be a canonical lucide slug — the tests
 * in this folder assert both on the whole table, so a lucide rename fails here
 * instead of in a user's grid. Still a seed table, not the full vocabulary: it
 * grows the same way, one hand-written pair at a time. A map generated by name
 * heuristics gets it badly wrong, starting with `build`, which is a wrench in
 * Material Symbols and nothing to do with construction.
 *
 * **Where the two vocabularies do not line up one-to-one.** Three recurring
 * shapes, all deliberate:
 *
 * - **Outline and filled are one glyph.** Material Symbols ships `favorite` and
 *   `favorite_border`, `check_circle` and `check_circle_outline`,
 *   `person` and `person_outline` as separate names. In lucide, filled versus
 *   outline is a rendering choice on one icon, so each pair lands on the same
 *   slug.
 * - **Tool and variant distinctions collapse.** `build`, `handyman` and
 *   `hardware` are all `wrench`; `pedal_bike`, `two_wheeler` and
 *   `delivery_dining` are all `bike`; the iOS chevrons (`arrow_back_ios`,
 *   `arrow_forward_ios`, `navigate_next`) are the plain chevrons; the five list
 *   glyphs (`view_list`, `list_alt`, `format_list_bulleted`, `reorder`) are
 *   `list`.
 * - **A few genuinely lose meaning**, and those are the ones to know about:
 *   `delete_forever` → `trash-2` drops "permanent"; `add_shopping_cart` →
 *   `shopping-cart` drops the "add"; `picture_as_pdf` → `file-text` because
 *   lucide has no PDF glyph; `face` → `face-slightly-smiling` turns a neutral
 *   face into a smiling one; `history` → `rotate-ccw-clock` is a clock with an
 *   arrow rather than a list of past events; `payments` → `wallet` turns a card stack into a wallet;
 *   `category` → `shapes`; `plumbing` → `shower-head`, because lucide has no
 *   pipe. Pass an explicit slug where that matters.
 *
 * The 37 identity pairs are here on purpose. Their names happen to match in both
 * vocabularies, so they already render today — leaving them out would send them
 * to {@link MATERIAL_SYMBOL_FALLBACK} and make this bridge a regression for
 * exactly the codes that used to work.
 *
 * @see fromMaterialSymbol — the lookup you normally call.
 */
export const materialToLucide: Readonly<Record<string, IconName>> = {
    account_balance: "landmark",
    account_balance_wallet: "wallet",
    account_box: "square-user",
    account_circle: "circle-user",
    add: "plus",
    add_circle: "circle-plus",
    add_circle_outline: "circle-plus",
    add_shopping_cart: "shopping-cart",
    admin_panel_settings: "shield-user",
    analytics: "chart-column",
    apps: "layout-grid",
    arrow_back: "arrow-left",
    arrow_back_ios: "chevron-left",
    arrow_back_ios_new: "chevron-left",
    arrow_downward: "arrow-down",
    arrow_drop_down: "chevron-down",
    arrow_forward: "arrow-right",
    arrow_forward_ios: "chevron-right",
    arrow_right: "chevron-right",
    arrow_right_alt: "arrow-right",
    arrow_upward: "arrow-up",
    article: "newspaper",
    assignment: "clipboard-list",
    attach_file: "paperclip",
    attach_money: "dollar-sign",
    autorenew: "refresh-cw",
    badge: "id-card",
    bolt: "zap",
    bookmark: "bookmark",
    brush: "brush",
    build: "wrench",
    business: "building-2",
    calendar_month: "calendar",
    calendar_today: "calendar",
    call: "phone",
    campaign: "megaphone",
    cancel: "circle-x",
    category: "shapes",
    chat: "message-circle",
    check: "check",
    check_box: "square-check",
    check_box_outline_blank: "square",
    check_circle: "circle-check",
    check_circle_outline: "circle-check",
    chevron_left: "chevron-left",
    chevron_right: "chevron-right",
    circle: "circle",
    clear: "x",
    close: "x",
    code: "code",
    construction: "construction",
    content_copy: "copy",
    credit_card: "credit-card",
    dark_mode: "moon",
    dashboard: "layout-dashboard",
    date_range: "calendar-range",
    delete: "trash-2",
    delete_forever: "trash-2",
    delete_outline: "trash-2",
    delivery_dining: "bike",
    description: "file-text",
    done: "check",
    done_all: "check-check",
    download: "download",
    east: "arrow-right",
    edit: "pencil",
    edit_note: "pencil-line",
    electrical_services: "plug-zap",
    email: "mail",
    emoji_events: "trophy",
    engineering: "hard-hat",
    error: "circle-alert",
    error_outline: "circle-alert",
    event: "calendar-days",
    expand_less: "chevron-up",
    expand_more: "chevron-down",
    explore: "compass",
    face: "face-slightly-smiling",
    fact_check: "clipboard-check",
    favorite: "heart",
    favorite_border: "heart",
    file_download: "download",
    file_upload: "upload",
    filter_alt: "funnel",
    filter_list: "funnel",
    fingerprint: "fingerprint-pattern",
    folder: "folder",
    format_list_bulleted: "list",
    format_paint: "paint-roller",
    gavel: "gavel",
    grade: "star",
    grid_view: "layout-grid",
    group: "users",
    groups: "users",
    handyman: "wrench",
    hardware: "wrench",
    help: "circle-question-mark",
    help_outline: "circle-question-mark",
    highlight_off: "circle-x",
    history: "rotate-ccw-clock",
    home: "house",
    image: "image",
    info: "info",
    insights: "chart-line",
    inventory: "package",
    inventory_2: "package",
    key: "key",
    language: "globe",
    light_mode: "sun",
    lightbulb: "lightbulb",
    link: "link",
    list: "list",
    list_alt: "list",
    local_offer: "tag",
    local_shipping: "truck",
    location_on: "map-pin",
    lock: "lock",
    lock_open: "lock-open",
    login: "log-in",
    logout: "log-out",
    mail: "mail",
    mail_outline: "mail",
    manage_accounts: "user-cog",
    map: "map",
    menu: "menu",
    menu_book: "book-open",
    mic: "mic",
    mode_edit: "pencil",
    monetization_on: "circle-dollar-sign",
    more_horiz: "ellipsis",
    more_vert: "ellipsis-vertical",
    navigate_next: "chevron-right",
    note_add: "file-plus",
    notifications: "bell",
    notifications_active: "bell-ring",
    open_in_new: "external-link",
    paid: "circle-dollar-sign",
    palette: "palette",
    pause: "pause",
    payments: "wallet",
    pedal_bike: "bike",
    people: "users",
    perm_identity: "user",
    person: "user",
    person_add: "user-plus",
    person_outline: "user",
    pets: "paw-print",
    phone: "phone",
    phone_iphone: "smartphone",
    photo_camera: "camera",
    picture_as_pdf: "file-text",
    place: "map-pin",
    play_arrow: "play",
    play_circle: "circle-play",
    play_circle_filled: "circle-play",
    plumbing: "shower-head",
    power_settings_new: "power",
    print: "printer",
    public: "globe",
    qr_code_scanner: "scan-line",
    question_answer: "messages-square",
    radio_button_checked: "circle-dot",
    radio_button_unchecked: "circle",
    receipt: "receipt",
    receipt_long: "receipt-text",
    refresh: "refresh-cw",
    remove: "minus",
    remove_circle_outline: "circle-minus",
    reorder: "list",
    report_problem: "triangle-alert",
    restart_alt: "rotate-ccw",
    room: "map-pin",
    router: "router",
    save: "save",
    savings: "piggy-bank",
    schedule: "clock",
    school: "graduation-cap",
    search: "search",
    send: "send",
    settings: "settings",
    share: "share-2",
    shield: "shield",
    shopping_bag: "shopping-bag",
    shopping_cart: "shopping-cart",
    smartphone: "smartphone",
    sort: "arrow-down-up",
    star: "star",
    star_border: "star",
    star_rate: "star",
    store: "store",
    storefront: "store",
    support_agent: "headset",
    task_alt: "circle-check",
    timer: "timer",
    today: "calendar",
    toggle_on: "toggle-right",
    trending_up: "trending-up",
    tune: "sliders-horizontal",
    tv: "tv",
    two_wheeler: "bike",
    upload_file: "upload",
    verified: "badge-check",
    verified_user: "shield-check",
    videocam: "video",
    view_list: "list",
    visibility: "eye",
    visibility_off: "eye-off",
    vpn_key: "key-round",
    warehouse: "warehouse",
    warning: "triangle-alert",
    warning_amber: "triangle-alert",
    watch_later: "clock",
    wifi: "wifi",
    work: "briefcase",
};

/**
 * Translate a Material Symbols code into a lucide slug, always returning one.
 *
 * Never returns `undefined`: an unknown code resolves to `fallback`, so a row
 * whose `icon_code` this table has not learned yet still renders. The input is
 * trimmed and lower-cased before lookup, because a seed written by hand is the
 * kind of source that carries stray whitespace and the odd capital.
 *
 * Nothing else in `/icons` imports this module, so an app that does not store
 * Material Symbols never pays for the table.
 *
 * @example
 * <Icon name={fromMaterialSymbol(category.icon_code)} size={20} />
 *
 * @example
 * <Icon name={fromMaterialSymbol(category.icon_code, "folder")} size={20} />
 *
 * @param code - A Material Symbols name, or `null`/`undefined` for a row that has none.
 * @param fallback - Slug to use when `code` is empty or unknown. Defaults to {@link MATERIAL_SYMBOL_FALLBACK}.
 * @returns A lucide slug `<Icon>` can render.
 */
export function fromMaterialSymbol(
    code: string | null | undefined,
    fallback: IconName = MATERIAL_SYMBOL_FALLBACK,
): IconName {
    if (!code) return fallback;
    return materialToLucide[code.trim().toLowerCase()] ?? fallback;
}
