import type { IconName } from "./generated/icon-name";

/**
 * The slug `fromMaterialSymbol` falls back to when a code is unknown.
 *
 * A neutral glyph rather than nothing: a category created in an admin with a
 * code this table has not learned yet still has to draw something, or it opens a
 * hole in the grid and the bug reads as a layout problem instead of a missing
 * mapping.
 *
 * Lucide's `circle-help` is a deprecated alias of this slug. `<Icon>` resolves
 * aliases, so both render — but the bridge emits the canonical name, since a
 * value that gets persisted should not be one lucide has already renamed.
 */
export const MATERIAL_SYMBOL_FALLBACK: IconName = "circle-question-mark";

/**
 * Material Symbols code → lucide slug, for backends that store `icon_code`.
 *
 * Every Python backend we write stores a category icon as a Material Symbol
 * (`build`, `format_paint`, `electrical_services`) — the vocabulary Flutter,
 * Android and the administrative seeds already speak. The SDK speaks lucide in
 * kebab-case. The two lists do not meet, and the failure is nastier than an
 * empty screen: a handful of codes collide by accident, so roughly one row in
 * ten draws the right icon and the bug reads as "some icons went missing".
 *
 * **This is a seed table, not the full vocabulary.** Material Symbols ships
 * ~3600 names and almost none of them will ever appear in an `icon_code` of
 * ours. It grows on demand, one hand-written pair at a time — a map generated by
 * name heuristics gets it badly wrong, starting with `build`, which is a wrench
 * in Material Symbols and not anything to do with construction.
 *
 * **Approximations, deliberate and not one-to-one:**
 *
 * - `plumbing` → `shower-head`, because lucide has no pipe.
 * - `build`, `handyman` and `hardware` all land on `wrench` — Material Symbols
 *   distinguishes the tools, lucide does not.
 * - `pedal_bike`, `two_wheeler` and `delivery_dining` all land on `bike`.
 *
 * The thirteen identity pairs are here on purpose. Their names happen to match
 * in both vocabularies, so they already render today — leaving them out would
 * send them to {@link MATERIAL_SYMBOL_FALLBACK} and make this bridge a
 * regression for exactly the codes that used to work.
 *
 * @see fromMaterialSymbol — the lookup you normally call.
 */
export const materialToLucide: Readonly<Record<string, IconName>> = {
    brush: "brush",
    build: "wrench",
    code: "code",
    delivery_dining: "bike",
    electrical_services: "plug-zap",
    format_paint: "paint-roller",
    gavel: "gavel",
    handyman: "wrench",
    hardware: "wrench",
    key: "key",
    lock: "lock",
    mic: "mic",
    palette: "palette",
    pedal_bike: "bike",
    plumbing: "shower-head",
    router: "router",
    settings: "settings",
    shield: "shield",
    smartphone: "smartphone",
    tv: "tv",
    two_wheeler: "bike",
    warehouse: "warehouse",
};

/**
 * Translate a Material Symbols code into a lucide slug, always returning one.
 *
 * Never returns `undefined`: an unknown code resolves to `fallback`, so a row
 * whose `icon_code` this table has not learned yet still renders. The input is
 * trimmed and lower-cased before lookup, because a seed written by hand is the
 * kind of source that carries stray whitespace and the odd capital.
 *
 * Nothing else in `/icons` imports this module, so an app that does not store
 * Material Symbols never pays for the table.
 *
 * @example
 * <Icon name={fromMaterialSymbol(category.icon_code)} size={20} />
 *
 * @example
 * <Icon name={fromMaterialSymbol(category.icon_code, "folder")} size={20} />
 *
 * @param code - A Material Symbols name, or `null`/`undefined` for a row that has none.
 * @param fallback - Slug to use when `code` is empty or unknown. Defaults to {@link MATERIAL_SYMBOL_FALLBACK}.
 * @returns A lucide slug `<Icon>` can render.
 */
export function fromMaterialSymbol(
    code: string | null | undefined,
    fallback: IconName = MATERIAL_SYMBOL_FALLBACK,
): IconName {
    if (!code) return fallback;
    return materialToLucide[code.trim().toLowerCase()] ?? fallback;
}
