// Generate the slug → icon-component tables that back `tempest-react-sdk/icons`.
//
// Reads the installed `lucide-react` and emits `src/icons/generated/`. Run it
// after bumping lucide:
//
//   npm run gen:icons
//
// The tables re-export from `lucide-react` instead of vendoring icon path data,
// so the icons a consuming app renders always come from the lucide version that
// app installed.
//
// Every emitted module goes through prettier with the repo's own config before
// it is written. That is what lets `.github/workflows/ci.yml` run this script
// and fail on a non-empty `git diff`: unformatted output would make the diff
// non-empty on every run, and the guard would be noise instead of a signal.
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { format, resolveConfig } from "prettier";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ICONS_DIR = join(ROOT, "node_modules", "lucide-react", "dist", "esm", "icons");
const OUT_DIR = join(ROOT, "src", "icons", "generated");
const DOCS_ASSET_DIR = join(ROOT, "docs", "assets");

const BANNER = `// GENERATED by scripts/gen-icons.mjs — do not edit.
// Run \`npm run gen:icons\` after bumping lucide-react.
`;

/**
 * A canonical icon module declares its component and its slug in one call:
 *
 *     const AlignHorizontalDistributeCenter = createLucideIcon(
 *         "align-horizontal-distribute-center",
 *         __iconNode,
 *     );
 *
 * The `\s*` after the paren matters — nine modules wrap the arguments onto
 * separate lines, and a single-line-only pattern silently drops them.
 */
const CANONICAL = /const (\w+) = createLucideIcon\(\s*"([^"]+)"/;

/** A deprecated alias module is a bare re-export: `export { default } from './circle-alert.mjs'`. */
const ALIAS = /export \{ default \} from '\.\/([^']+)\.mjs'/;

/**
 * Read every icon module and split it into canonical icons and aliases.
 *
 * Throws when the two groups plus `index.mjs` do not add up to the file count:
 * a lucide release that changes the emitted shape must fail the build loudly
 * rather than produce a table that is quietly missing icons.
 *
 * @returns {Promise<{ canonical: Map<string, string>, aliases: Map<string, string> }>}
 *   `canonical` maps slug → PascalCase export name; `aliases` maps alias slug →
 *   canonical slug.
 */
async function readIconModules() {
    const files = (await readdir(ICONS_DIR)).filter((f) => f.endsWith(".mjs"));
    const canonical = new Map();
    const aliases = new Map();
    const unrecognized = [];

    for (const file of files) {
        if (file === "index.mjs") continue;
        const slug = file.slice(0, -".mjs".length);
        const source = await readFile(join(ICONS_DIR, file), "utf8");
        const asCanonical = CANONICAL.exec(source);
        if (asCanonical) {
            canonical.set(asCanonical[2], asCanonical[1]);
            continue;
        }
        const asAlias = ALIAS.exec(source);
        if (asAlias) {
            aliases.set(slug, asAlias[1]);
            continue;
        }
        unrecognized.push(file);
    }

    if (unrecognized.length) {
        throw new Error(
            `gen-icons: ${unrecognized.length} icon module(s) matched neither the canonical nor the alias shape — ` +
                `lucide-react's output changed. First few: ${unrecognized.slice(0, 5).join(", ")}`,
        );
    }
    const accounted = canonical.size + aliases.size + 1;
    if (accounted !== files.length) {
        throw new Error(
            `gen-icons: parsed ${accounted} of ${files.length} files in ${ICONS_DIR}. Refusing to emit a partial table.`,
        );
    }
    return { canonical, aliases };
}

/**
 * Bucket canonical icons by the first character of their slug.
 *
 * One shard per initial letter is the compromise the module graph allows: a
 * single chunk with every icon would cost every app the whole set, and a chunk
 * per icon is the ~2000-request problem this module exists to avoid. Lucide
 * currently spans 25 letters (there is no `y` icon), and the largest bucket is
 * around 10 KB brotli.
 *
 * @param {Map<string, string>} canonical - slug → PascalCase export name.
 * @returns {Map<string, Map<string, string>>} letter → (slug → export name).
 */
function shard(canonical) {
    const shards = new Map();
    for (const [slug, name] of [...canonical].sort(([a], [b]) => a.localeCompare(b))) {
        const letter = slug[0];
        if (!shards.has(letter)) shards.set(letter, new Map());
        shards.get(letter).set(slug, name);
    }
    return new Map([...shards].sort(([a], [b]) => a.localeCompare(b)));
}

/**
 * Export names that would shadow a restricted global if bound directly.
 *
 * Lucide ships an icon literally called `infinity`, whose export is `Infinity`.
 * Binding that at module scope shadows the global and is a lint error, so the
 * import is aliased instead.
 */
const RESERVED_NAMES = new Set(["Infinity", "NaN", "undefined", "eval", "arguments"]);

/**
 * The local binding to use for a lucide export name.
 *
 * @param {string} name - The PascalCase lucide export name.
 * @returns {string} A safe local identifier.
 */
function localName(name) {
    return RESERVED_NAMES.has(name) ? `${name}Icon` : name;
}

/**
 * Serialize one shard module: static named imports plus the slug table.
 *
 * The imports must be **named**, never `import * as lucide`. A namespace import
 * looks tidier and costs the type-checker far less, but it makes every shard
 * depend on the whole of `lucide-react`: a bundler then hoists all ~2000 icons
 * into one shared chunk, and importing `Icon` alone measured 130 KB brotli
 * instead of ~1 KB. Named imports are what lets each shard carry only its own
 * letter.
 */
function shardModule(letter, entries) {
    const imports = [...entries.values()]
        .sort()
        .map((name) => (localName(name) === name ? name : `${name} as ${localName(name)}`));
    const table = [...entries]
        .map(([slug, name]) => `    "${slug}": ${localName(name)},`)
        .join("\n");
    return `${BANNER}
import { ${imports.join(", ")} } from "lucide-react";
import type { LucideIcon } from "lucide-react";

/** The ${entries.size} lucide icons whose slug starts with "${letter}". */
const shard: Record<string, LucideIcon> = {
${table}
};

export default shard;
`;
}

/** Serialize the lazy loader table — the only place shards are referenced. */
function loadersModule(letters) {
    const table = letters
        .map((letter) => `    ${letter}: () => import("./shard-${letter}"),`)
        .join("\n");
    return `${BANNER}
import type { LucideIcon } from "lucide-react";

/**
 * One dynamic import per initial letter.
 *
 * These are the only references to the shard modules, which is what keeps them
 * out of whatever chunk imports \`Icon\`: a bundler that sees no static edge to a
 * shard emits it as an async chunk fetched on first use.
 */
export const shardLoaders: Record<
    string,
    () => Promise<{ default: Record<string, LucideIcon> }>
> = {
${table}
};
`;
}

/** Serialize the alias table: deprecated slug → the slug that still exists. */
function aliasesModule(aliases) {
    const table = [...aliases]
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([from, to]) => `    "${from}": "${to}",`)
        .join("\n");
    return `${BANNER}
/**
 * Lucide's ${aliases.size} deprecated slugs, mapped to the canonical slug that
 * replaced them (\`alert-circle\` → \`circle-alert\`).
 *
 * Kept so a name stored in a database years ago keeps rendering after a lucide
 * bump renames it. Resolution goes through here first, so an alias loads the
 * shard of its *canonical* slug.
 */
export const iconAliases: Record<string, string> = {
${table}
};
`;
}

/**
 * Serialize the slug array.
 *
 * Deliberately its own module: at ~6 KB brotli it is the single heaviest piece
 * of this feature, and only an icon *picker* needs it. `Icon` never imports it.
 */
function iconNamesModule(slugs) {
    const table = slugs.map((slug) => `    "${slug}",`).join("\n");
    return `${BANNER}
import type { IconName } from "./icon-name";

/**
 * Every addressable icon slug — canonical names plus deprecated aliases,
 * ${slugs.length} in total, sorted.
 *
 * Importing this pulls in the whole list (~6 KB brotli). Reach for it when you
 * are building a picker; \`<Icon>\` itself does not need it.
 */
export const iconNames: readonly IconName[] = [
${table}
];
`;
}

/** Serialize the `IconName` union — types only, so it costs nothing at runtime. */
function iconNameModule(slugs) {
    const union = slugs.map((slug) => `    | "${slug}"`).join("\n");
    return `${BANNER}
/**
 * Every icon slug lucide ships, as a union of string literals.
 *
 * Erased at compile time, so the ${slugs.length} members cost no bytes — they buy
 * autocomplete and a typo caught by \`tsc\` instead of at runtime.
 */
export type IconName =
${union};
`;
}

/**
 * Serialize the slug reference published with the docs site.
 *
 * Two files rather than one, because they answer two different questions. The
 * CSV is the whole picture — every slug with whether it is canonical or
 * deprecated, and what a deprecated one resolves to — for someone deciding what
 * a backend may store. The plain list is the one a `grep`, a seed script or a
 * database CHECK constraint actually wants: only names that are safe to write
 * today.
 *
 * Emitted from here so the files cannot drift from `iconNames`: a lucide bump
 * that renames an icon rewrites both in the same run that rewrites the tables.
 *
 * @param canonical - Slug → PascalCase export name, canonical icons only.
 * @param aliases - Alias slug → canonical slug.
 * @returns `{ csv, txt }`, ready to write.
 */
function slugReference(canonical, aliases) {
    const rows = [
        ...[...canonical.keys()].map((slug) => `${slug},canonical,${slug}`),
        ...[...aliases].map(([from, to]) => `${from},deprecated,${to}`),
    ].sort((a, b) => a.localeCompare(b));

    return {
        csv: `slug,status,canonical\n${rows.join("\n")}\n`,
        txt: `${[...canonical.keys()].sort((a, b) => a.localeCompare(b)).join("\n")}\n`,
    };
}

async function main() {
    const { canonical, aliases } = await readIconModules();
    const shards = shard(canonical);
    const slugs = [...canonical.keys(), ...aliases.keys()].sort((a, b) => a.localeCompare(b));

    await rm(OUT_DIR, { recursive: true, force: true });
    await mkdir(OUT_DIR, { recursive: true });

    const written = [];
    const prettierOptions = await resolveConfig(join(OUT_DIR, "any.ts"));
    const write = async (name, contents) => {
        const path = join(OUT_DIR, name);
        await writeFile(path, await format(contents, { ...prettierOptions, filepath: path }));
        written.push(name);
    };

    for (const [letter, entries] of shards) {
        await write(`shard-${letter}.ts`, shardModule(letter, entries));
    }
    await write("loaders.ts", loadersModule([...shards.keys()]));
    await write("aliases.ts", aliasesModule(aliases));
    await write("icon-name.ts", iconNameModule(slugs));
    await write("icon-names.ts", iconNamesModule(slugs));

    const reference = slugReference(canonical, aliases);
    await mkdir(DOCS_ASSET_DIR, { recursive: true });
    await writeFile(join(DOCS_ASSET_DIR, "icon-slugs.csv"), reference.csv);
    await writeFile(join(DOCS_ASSET_DIR, "icon-slugs.txt"), reference.txt);

    console.log(
        `gen-icons: ${canonical.size} canonical + ${aliases.size} alias = ${slugs.length} slugs`,
    );
    console.log("gen-icons: wrote icon-slugs.csv + icon-slugs.txt to docs/assets/");
    console.log(`gen-icons: ${shards.size} shards (${[...shards.keys()].join("")})`);
    console.log(`gen-icons: wrote ${written.length} files to src/icons/generated/`);
}

await main();
